### ISSUE TITLE
Tooltips display as blank

### ISSUE THREAD

**Issue by PaCozz** [casualshammy/DeathNote#18]
Hovering over the Time, HP, Amount text or Source text only display a blank tooltip box with no information within.

Steps to reproduce:
1. Collect data (deaths) in any content in WoW:Dragonflight
2. Open Death Note addon
3. Select any death and hover mouse over HP bar
4. Observe result
5. Hover mouse over Amount numbers/text
6. Observe result
7. Hover mouse over Source names
8. Observe result
9. Hover mouse over Time
10. Observe result

Expected results:
Show relevant time stamps.
Show health as numbers / percentages and max health.
Show information about the event that happened as text.

Observed results:
Blank tooltip boxes containing no information.

**Comment by lowpita** [comment]
Hey. Same here. Got these errors while opening the addon frame in combat, while dead, and out of combat, respectively:

35x FrameXML/GameTooltip.lua:190: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML/GameTooltip.lua"]:190: in function <FrameXML/GameTooltip.lua:172>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@FrameXML/GameTooltip.lua"]:954: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1476: in function <FrameXML/UIParent.lua:1399>

Locals:
Skipped (In Encounter)

8x SharedXML/SharedUIPanelTemplates.lua:525: attempt to index field 'Text' (a nil value)
[string "@SharedXML/SharedUIPanelTemplates.lua"]:525: in function `PanelTemplates_TabResize'
[string "*DeprecatedTemplates.xml:78_OnShow"]:1: in function <[string "*DeprecatedTemplates.xml:78_OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@DeathNote/UI.lua"]:1223: in function `ToggleFiltersFrame'
[string "@DeathNote/UI.lua"]:900: in function <DeathNote/UI.lua:900>

Locals:
tab = DeathNoteFiltersTab1 {
 0 = <userdata>
 ntab = 1
 selectedTextY = -2
 deselectedTextY = -3
}
padding = 0
absoluteSize = nil
minWidth = nil
maxWidth = nil
absoluteTextSize = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Text' (a nil value)"
TAB_SIDES_PADDING = 20

**Comment by lowpita** [comment]
Hi. Errors still persist after today's update.

**Comment by casualshammy** [comment]
I hope this bug is fixed in `100002.2-release`
