### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by igorrebolj** [casualshammy/DeathNote#19]
Message: Interface/AddOns/DeathNote/Format.lua:596: attempt to call method 'SetHyperlink' (a nil value)
Time: Sat Dec 31 12:21:17 2022
Count: 35
Stack: Interface/AddOns/DeathNote/Format.lua:596: attempt to call method 'SetHyperlink' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface/AddOns/DeathNote/Format.lua"]:596: in function `FormatTooltipSource'
[string "@Interface/AddOns/DeathNote/UI.lua"]:1122: in function `column_onenter'
[string "@Interface/AddOns/DeathNote/UI.lua"]:2198: in function <Interface/AddOns/DeathNote/UI.lua:2190>

Locals: (*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by Merxxz** [comment]
This is happening because lftip doesn't have the method SetHyperlink. If you add Mixin(lftip, GameTooltipDataMixin) to UI.lua after line 1034 it will prevent the error. However, only tooltips from the spell column actually have any text.

However, after 'mixing-in' the method I began to get a bunch of weird lua errors related to GameToolTip, so maybe that's not the best solution.

**Comment by casualshammy** [comment]
I hope this bug is fixed in `100002.2-release`
